### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by brettz9**
- npm: Update devDeps.
- npm: Update mocha peer dep.

### CODE REVIEW

**Comment by munierujp** [comment]
@brettz9 Please resolve conflicts.

**Comment by brettz9** [comment]
Thanks for the review and merge! Resolved/rebased...

**Comment by munierujp** [comment]
@brettz9 Could you divide PR to keep clean commit logs and versioning?

- Add .editorconfig
- Add meta for package.json
- Add lint script
- Update dependencies

**Comment by brettz9** [comment]
By dividing the PR, do you mean 4 separate PRs? (I've already split into 4 commits, and can make separate PRs also if you wish.)

**Comment by munierujp** [comment]
@brettz9 

> do you mean 4 separate PRs?

That's right.

**Comment by brettz9** [comment]
Ok, I've added separate PRs and made this one focus just on updating devDeps.

**Comment by munierujp** [comment]
This PR will be merged after #21, #22.

**Comment by brettz9** [comment]
I've updated and rebased this. Note that it in updating Mocha further to 8.0, it also adds Mocha 8 as a new peer dep. option

**Comment by brettz9** [comment]
Oh, and thank you for the merges/reviews!

**Comment by brettz9** [comment]
Could you look to merge this and #24 ? Thanks!

**Comment by munierujp** [comment]
@brettz9 I'm sorry for the late reply :bow:
Could you divide PR to keep clean commit logs and versioning?

- Support Mocha 8.x
- update eslint package
- update eslint-config-standard package
- update eslint-plugin-import package
- update eslint-plugin-node package

BTW: We're planning to use Renovate for managing dependencies as [ts-examples](http://github.com/ts-examples) does.

**Comment by brettz9** [comment]
I've already divided this per your earlier instructions into the update of dependencies, and not eager to see the chance for yet more divisions if you are not actually happy with those (e.g., if you change your mind to want mocha 8 for examples and mocha 8 for the main).

Besides that, there may be interactions where one update requires another update, so at this point, I'm just going to leave this in your hands. Thanks for the other merges...

**Pull request closed without merging**
